#!/bin/bash

#
# Bash shell functions for Git. 
#

set -e
set -u

# Die with error message.
exit_error() # {{{
{
	echo "$0: Error: $*" >&2
	exit 1
} # }}}

assert_dir() # {{{
{
    local dir=${1:-}

    if [[ ! -d "$dir" ]]; then
        return 1
    fi
} # }}}

assert_file() # {{{
{
    local file=${1:-}

    if [[ ! -f "$file" ]]; then
        return 1
    fi
} # }}}

branches_all() # {{{
{
	for branch in $(git branch | sed 's/\n//' | sed 's/^*//'); do
		BRANCHES+=($branch)
	done
	echo "${BRANCHES[*]}"
} # }}}

tag_local_exists() { # {{{

    tag_given=$1

    tags=$(git tag)

    for tag in ${tags[*]}; do
        echo $tag
        if [[ "${tag_given}" == "${tag}" ]]; then 
            return
        fi
    done
    return 1
} # }}}

tag_remote_exists() { # {{{

    tag_given=$1
    remote=$2

    tags=$(git ls-remote $remote | grep refs/tags)

    for tag in ${tags[*]}; do
        echo $tag
        if [[ "${tag}" == "refs/tags/${tag_given}" ]]; then 
            return
        fi
    done
    return 1
} # }}}
