String tag = "${TAG}".trim()
String release_tag =  "${is_release_tag}".trim()

currentBuild.displayName="${tag}"

stage("Merge $tag to master") {
    node('master') {
        sh script: """ 
            cd /local/git/repos
            ./master_to_tag_all.sh "${tag}" "${release_tag}"
        """
        
        // notify Slack
        String msg="Just merged tag ${tag} to master in Github rel organization for repos:\n"
        fileName='/tmp/repos_merged.txt'
        def lines = new File(fileName)
        lines = readFile (file: fileName)
        line_count=0
        
        for (line in lines.readLines()) {
            String repo = line.replaceAll("^.*/","")
            msg+="<https://github.deutsche-boerse.de/dev/${repo}|https://github.deutsche-boerse.de/dev/${repo}>\n"
            
            if( line_count > 18 ) { // max 20 lines in Slack
                build job: "notify_slack", parameters: [ string(name: 'message', value: "${msg}") ]
                msg="Just merged tag ${tag} to master in Github rel organization for repos:\n"                   
                line_count=0
            }
            line_count++
        }    
        build job: "notify_slack", parameters: [ string(name: 'message', value: "${msg}") ]
    }
}
